VehicleApp/Models/ErrorViewModel.cs
using System;

namespace VehicleApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VehicleApp/Models/Vehicle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace VehicleApp.Models
{
    public class Vehicle
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Brand { get; set; }
        [Required]
        public string Model { get; set; }
        [Range(0,int.MaxValue, ErrorMessage = "Distance must be positive.")]
        public int Distance { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Price must be positive.")]
        public int Price { get; set; }
    }
}

VehicleApp/Controllers/VehicleController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VehicleApp.Data;
using VehicleApp.Models;

namespace VehicleApp.Controllers
{
    public class VehicleController : Controller
    {
        private readonly ApplicationDbContext _db;

        public VehicleController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Vehicle> objList = _db.Vehicles;    
            return View(objList);
        }

        // GET-create
        public IActionResult Create()
        {
            return View();
        }

        // POST-create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Vehicle obj)
        {
            if (ModelState.IsValid)
            {
                _db.Vehicles.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET-delete
        public IActionResult Delete(int? id)
        {
            if (id == null ||id == 0)
            {
                return NotFound();
            }
            var obj = _db.Vehicles.Find(id);
            if (obj == null) {
                return NotFound();
            }
            return View(obj);
        }

        // POST-delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Vehicles.Find(id);
            if(obj == null)
            {
                return NotFound();
            }
            _db.Vehicles.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET-update
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Vehicles.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        // POST-update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Vehicle obj)
        {
            if (ModelState.IsValid)
            {
                _db.Vehicles.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
    }
}

VehicleApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VehicleApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Vehicle" asp-action="Index">VehicleApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehicle" asp-action="Index">Vehicles</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - VehicleApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VehicleApp/Views/Vehicle/Create.cshtml
@model VehicleApp.Models.Vehicle

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Create vehicle</h2>
        </div>
        <div class="row">
            <div class="col-9">
                <div class="form-group col">
                    <div class="row">
                        <div class="col-3">
                            <label asp-for="Brand"></label>
                        </div>
                        <div class="col-6 p-1">
                            <input asp-for="Brand" class="form-control" />
                            <span asp-validation-for="Brand" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <label asp-for="Model"></label>
                        </div>
                        <div class="col-6 p-1">
                            <input asp-for="Model" class="form-control" />
                            <span asp-validation-for="Model" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <label asp-for="Distance"></label>
                        </div>
                        <div class="col-6 p-1">
                            <input asp-for="Distance" class="form-control" />
                            <span asp-validation-for="Distance" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <label asp-for="Price"></label>
                        </div>
                        <div class="col-6 p-1">
                            <input asp-for="Price" class="form-control" />
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-9 text-center row">
                            <div class="col">
                                <input type="submit" class="btn btn-info w-75" value="Create"/>
                            </div>
                            <div class="col">
                                <a class="btn btn-danger w-75" asp-controller="Vehicle" asp-action="Index">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
</form>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
}

VehicleApp/Views/Vehicle/Delete.cshtml
@model VehicleApp.Models.Vehicle

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />   
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Delete vehicle</h2>
        </div>
        <div class="row">
            <div class="col-9">
                <div class="form-group col">
                    <div class="row">
                        <div class="col-3">
                            <label asp-for="Brand"></label>
                        </div>
                        <div class="col-6 p-1">
                            <input asp-for="Brand" class="form-control" disabled />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <label asp-for="Model"></label>
                        </div>
                        <div class="col-6 p-1">
                            <input asp-for="Model" class="form-control" disabled />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <label asp-for="Distance"></label>
                        </div>
                        <div class="col-6 p-1">
                            <input asp-for="Distance" class="form-control" disabled />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <label asp-for="Price"></label>
                        </div>
                        <div class="col-6 p-1">
                            <input asp-for="Price" class="form-control"  disabled/>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-9 text-center row">
                            <div class="col">
                                <input type="submit" class="btn btn-danger w-75" value="Delete" />
                            </div>
                            <div class="col">
                                <a class="btn btn-primary w-75" asp-controller="Vehicle" asp-action="Index">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

VehicleApp/Views/Vehicle/Index.cshtml
@model IEnumerable<VehicleApp.Models.Vehicle> 

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Vehicles</h2>
        </div>
        <div class="col-6 text-right">
            <a class="btn btn-primary" asp-controller="Vehicle" asp-action="Create">Create new vehicle</a>
        </div>
    </div>
    <br/>

    @if(Model.Count() > 0) 
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Brand
                    </th>
                    <th>
                        Model
                    </th>
                    <th>
                        Distance
                    </th>
                    <th>
                        Price
                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach(var vehicle in Model)
                {
                <tr>
                    <td width="20%">@vehicle.Brand</td>
                    <td width="20%">@vehicle.Model</td>
                    <td width="20%">@vehicle.Distance</td>
                    <td width="20%">@vehicle.Price</td>
                    <td width="20%">
                        <div class="w-100 btn-group" role="group">
                            <a class="btn btn-primary mx-1" 
                               asp-controller="Vehicle" 
                               asp-action="Update"
                               asp-route-Id="@vehicle.Id">Update</a>
                            <a class="btn btn-danger mx-1" 
                               asp-controller="Vehicle" 
                               asp-action="Delete"
                               asp-route-Id="@vehicle.Id">Delete</a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No vehicles created yet.</p>
    }
</div>

VehicleApp/Views/Vehicle/Update.cshtml
@model VehicleApp.Models.Vehicle

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Update vehicle</h2>
        </div>
        <div class="row">
            <div class="col-9">
                <div class="form-group col">
                    <div class="row">
                        <div class="col-3">
                            <label asp-for="Brand"></label>
                        </div>
                        <div class="col-6 p-1">
                            <input asp-for="Brand" class="form-control" />
                            <span asp-validation-for="Brand" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <label asp-for="Model"></label>
                        </div>
                        <div class="col-6 p-1">
                            <input asp-for="Model" class="form-control" />
                            <span asp-validation-for="Model" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <label asp-for="Distance"></label>
                        </div>
                        <div class="col-6 p-1">
                            <input asp-for="Distance" class="form-control" />
                            <span asp-validation-for="Distance" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <label asp-for="Price"></label>
                        </div>
                        <div class="col-6 p-1">
                            <input asp-for="Price" class="form-control" />
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-9 text-center row">
                            <div class="col">
                                <input type="submit" class="btn btn-info w-75" value="Update" />
                            </div>
                            <div class="col">
                                <a class="btn btn-danger w-75" asp-controller="Vehicle" asp-action="Index">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}